api/urls.py
from django.urls import include, path
from rest_framework import routers
from django.conf import settings

from . import views

app_name = 'rowapi'

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)
# router.register(r'profile', views.ProfileViewSet)
router.register(r'customer_profile', views.CustomerProfileViewSet)
router.register(r'product_view', views.ProductViewSet)
# router.register(r'product', views.ProductTextViewSet)
router.register(r'order_info', views.OrderInfoViewSet, base_name='order_info')
router.register(r'cart_design', views.CartDesignViewSet, base_name='cart_design')
# router.register(r'user_profile', views,ProfileViewSet)

urlpatterns = router.urls
# if settings.DEBUG:
#     urlpatterns += [
#         path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
#     ]

conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path, include
)

urlpatterns = [
    path('minsmine/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('design/', include('design.urls')),
    path('', include('design.urls')),
    path('clovi/', include('managing.urls')),
    path('rowapi/', include('api.urls', namespace='rowapi')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

design/urls.py
from django.urls import path
from . import views
app_name = 'design'

urlpatterns = [

    path('', views.HomeView.as_view(), name='home'),
    path('home_image/', views.HomeImageAPI.as_view(), name='home_image'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_change/', views.change_password, name='change_password'),
    path('product/', views.ProductView.as_view(), name='product'),
    path('cart/', views.CartProductView.as_view(), name='cart'),
    path('product/get_price/', views.AjaxPriceView.as_view(), name='get_price'),
    path('product_sample/', views.ProductSampleView.as_view(), name='product_sample'),
    path('product_confirm/', views.ProductConfirmView.as_view(), name='product_confirm'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('join/', views.JoinView.as_view(), name='join'),
    path('sample/', views.SampleListView.as_view(), name='sample'),
    path('sample_api/', views.SampleAPIView.as_view(), name='sample_api'),
    path('faq/', views.FaqView.as_view(), name='faq'),
    path('notice/', views.NewsView.as_view(), name='news'),
    path('order_list/', views.OrderListView.as_view(), name='order_list'),
    path('order_list/detail/', views.CustomerOrderListView.as_view(), name='order_list_detail'),
    path('my_page/', views.MyPageView.as_view(), name='my_page'),

]

design/models.py
import uuid
import datetime
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from imagekit.models import ProcessedImageField
from model_utils import Choices
from model_utils.models import SoftDeletableModel, TimeStampedModel
from mptt.fields import TreeForeignKey
from mptt.managers import TreeManager
from mptt.models import MPTTModel
from pilkit.processors import ResizeToFit


class Category(TimeStampedModel, MPTTModel):
    parent = TreeForeignKey(
        'self',
        verbose_name=_('parent'),
        blank=True,
        null=True,
        related_name='children',
        db_index=True,
        on_delete=models.SET_NULL,
    )

    title = models.CharField(
        verbose_name=_('title'),
        max_length=128,
    )

    class MPTTMeta:
        order_insertion_by = ['created']

    class Meta:
        verbose_name = _('카테고리 품목')
        verbose_name_plural = _('카테고리 품목')

    def __str__(self):
        return f'{self.title}'


class SectorsCategory(TimeStampedModel, MPTTModel):
    parent = TreeForeignKey(
        'self',
        verbose_name=_('parent'),
        blank=True,
        null=True,
        related_name='children',
        db_index=True,
        on_delete=models.SET_NULL,
    )

    title = models.CharField(
        verbose_name=_('title'),
        max_length=128,
    )

    class MPTTMeta:
        order_insertion_by = ['created']

    class Meta:
        verbose_name = _('카테고리 업종')
        verbose_name_plural = _('카테고리 업종')

    objects = TreeManager()

    def __str__(self):
        return f'{self.title}'


class Option(TimeStampedModel, SoftDeletableModel, MPTTModel):
    category = models.ForeignKey(
        'design.Category',
        verbose_name=_('category'),
        related_name='options',
        null=True,
        db_index=True,
        on_delete=models.SET_NULL,
    )

    parent = TreeForeignKey(
        'self',
        verbose_name=_('parent'),
        blank=True,
        null=True,
        related_name='children',
        db_index=True,
        on_delete=models.SET_NULL,
    )

    title = models.CharField(
        verbose_name=_('title'),
        max_length=128,
    )

    slug = models.SlugField(
        verbose_name=_('slug'),
        help_text=_('A short label containing only letters, numbers, underscores or hyphens for URL'),
        max_length=255,
        unique=True,
        allow_unicode=True,
    )

    class MPTTMeta:
        order_insertion_by = ['created']

    class Meta:
        verbose_name = _('상품옵션 기타')
        verbose_name_plural = _('상품옵션 기타')

    def __str__(self):
        return f'{self.title}'

class ProductText(TimeStampedModel, SoftDeletableModel):
    category = models.ForeignKey(
        'design.Category',
        verbose_name=_('카테고리'),
        blank=True,
        null=True,
        db_index=True,
        on_delete=models.SET_NULL,
    )

    supplier = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        verbose_name=_('매입처'),
        blank=True,
        null=True,
    )

    standard = models.CharField(
        max_length=255,
        verbose_name=_('규격명'),
        null=True,
        blank= True,
    )
    horizontal = models.DecimalField(
        verbose_name=_('가로'),
        max_digits=11,
        decimal_places=4,
        default=0,
        null=True,
        blank=True,
    )
    vertical = models.DecimalField(
        verbose_name=_('세로'),
        max_digits=11,
        decimal_places=4,
        default=0,
        null=True,
        blank=True,
    )
    width = models.DecimalField(
        verbose_name=_('넓이'),
        max_digits=11,
        decimal_places=4,
        default=0,
        null=True,
        blank=True,
    )
    height = models.DecimalField(
        verbose_name=_('높이'),
        max_digits=11,
        decimal_places=4,
        default=0,
        null=True,
        blank=True,
    )

    paper = models.CharField(
        verbose_name=_('재질'),
        max_length=255,
        blank=True,
        null=True,

    )

    gram = models.CharField(
        verbose_name=_('그람수'),
        blank=True,
        null=True,
        max_length=100,
    )

    color = models.CharField(
        verbose_name=_('색상'),
        blank=True,
        null=True,
        max_length=100,
    )

    paper_option = models.CharField(
        verbose_name=_('옵션 코팅/유무'),
        blank=True,
        null=True,
        max_length=100,
    )

    side = models.CharField(
        verbose_name=_('양면 / 단면'),
        blank=True,
        null=True,
        max_length=100,
    )

    etc = models.CharField(
        verbose_name=_('기타 정보'),
        blank=True,
        null=True,
        max_length=100,
    )
    etc_option = models.CharField(
        verbose_name=_('기타 옵션 상세'),
        blank=True,
        null=True,
        max_length=100,
    )

    memo = models.CharField(
        verbose_name=_('기타 옵션 메모'),
        blank=True,
        null=True,
        max_length=100,
    )

    code = models.IntegerField(
        verbose_name=_('품목코드'),
        null=True,
        blank=True,
    )

    title = models.CharField(
        verbose_name=_('품목명'),
        null=True,
        blank=True,
        max_length=128,
    )

    slug = models.SlugField(
        verbose_name=_('slug'),
        max_length=255,
        null=True,
        blank=True,
        unique=True,
        allow_unicode=True,
    )

    sell_price = models.DecimalField(
        verbose_name=_('판매가'),
        max_digits=11,
        decimal_places=4,
        default=0,
        null=True,
        blank=True,
    )

    buy_price = models.DecimalField(
        verbose_name=_('매입가'),
        max_digits=11,
        decimal_places=4,
        default=0,
        null=True,
        blank=True,
    )

    quantity = models.DecimalField(
        verbose_name=_('메인 수량'),
        max_digits=11,
        decimal_places=4,
        default=0,
        null=True,
        blank=True,
    )

    main_quantity = models.BooleanField(
        verbose_name=_('메인 수량'),
        default = False,
    )

    ecount = models.BooleanField(
        verbose_name=_('이카운트 전송'),
        default=True,
    )

    product_active = models.BooleanField(
        verbose_name=_('활성화'),
        default = False,
    )
    product_version = models.IntegerField(
        verbose_name=_('version'),
        default=1,
        blank=True,
        null=True,
    )
    group = models.IntegerField(
        verbose_name=_('group'),
        blank=True,
        null=True,
    )

    @property
    def benefit(self):
        if self.sell_price and self.buy_price:
            data = 0
            try:
                data = self.buy_price / self.sell_price * 100
                data = 100-data
                return data
            except:
                return data

    class Meta:
        verbose_name = _('상품옵션_통합 str')
        verbose_name_plural = _('상품옵션_통합 str')

    def __str__(self):
        return f'{self.title}'

class OrderInfo(TimeStampedModel, SoftDeletableModel):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('거래처'),
        null=True,
        blank=True,
        db_index=True,
        on_delete=models.SET_NULL,
    )

    today_num = models.IntegerField(
        verbose_name=_('today-넘버링'),
        default=1,
    )

    joo_date = models.DateField(
        verbose_name=_('주문일'),
        null=True,
        blank=True,
    )

    order_date = models.DateField(
        verbose_name=_('발주일'),
        null=True,
        blank=True,
    )

    company = models.CharField(
        verbose_name=_('업체명'),
        max_length=255,
        null=True,
        blank=True,
    )
    company_keyword = models.CharField(
        verbose_name=_('업체 키워드'),
        max_length=255,
        null=True,
        blank=True,
    )

    address = models.CharField(
        verbose_name=_('주소'),
        max_length=255,
        null=True,
        blank=True,
    )
    tell = models.CharField(
        verbose_name=_('연락처'),
        max_length=255,
        null=True,
        blank=True,
    )

    STATE_WHAT = Choices(
        (0, '견적', _('견적')),
        (1, '주문', _('주문')),
        (2, '시안', _('시안')),
        (3, '제작', _('제작')),
        (4, '완료', _('완료')),
        (5, '취소', _('취소')),
        (6, '보류', _('보류')),
        (7, '환불', _('환불')),
        (8, '입금대기', _('입금대기')),
        (9, '배송', _('배송')),
    )

    state = models.IntegerField(
        verbose_name=_('상태값'),
        choices=STATE_WHAT,
        default=0,
        blank=True,
        db_index=True,
    )


    tax = models.BooleanField(
        verbose_name=_('부가세포함'),
        default=True,
    )

    keywords = models.CharField(
        verbose_name=_('검색창 내용'),
        max_length=1000,
        null=True,
        blank=True,
    )

    checker = models.CharField(
        verbose_name=_('시안 확인'),
        max_length=255,
        null=True,
        blank=True,
    )
    deposit = models.CharField(
        verbose_name=_('입금 확인'),
        max_length=100,
        null=True,
        blank=True,
    )
    options = models.CharField(
        verbose_name=_('결제/포함/택배'),
        max_length=255,
        null=True,
        blank=True,
    )

    employees = models.CharField(
        verbose_name=_('작업자'),
        null=True,
        blank=True,
        max_length=100,
        db_index=True,
    )

    fix_manager = models.CharField(
        verbose_name=_('담당자'),
        null=True,
        blank=True,
        max_length=100,
        db_index=True,
    )

    in_memo = models.CharField(
        verbose_name=_('관리자메모'),
        max_length=1000,
        null=True,
        blank=True,
    )

    out_memo = models.CharField(
        verbose_name=_('고객표시 메모'),
        max_length=1000,
        null=True,
        blank=True,
    )

    deposit_check = models.IntegerField(
        verbose_name=_('입금 확인 및 차액'),
        null=True,
        blank=True,
    )

    uuid = models.UUIDField(

design/forms.py
from django import forms
from design import models as design_model
from member import models as member_model
from managing import models as managing_model
from allauth.account.forms import LoginForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class OrderProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['code'].widget.attrs.update({'class': 'form-control'})
        self.fields['company'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control' ,'readonly':'readonly'})
        self.fields['address2'].widget.attrs.update({'class': 'form-control' ,'readonly':'readonly'})
        self.fields['address_detail'].widget.attrs.update({'class': 'form-control'})
        self.fields['address_option'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone'].widget.attrs.update({'class': 'form-control'})
        self.fields['bill_select'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = member_model.CustomerProfile
        fields = ['company','code','phone','address','address2','address_detail','address_option','bill_select']

class CustomerProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['code'].widget.attrs.update({'class': 'form-control'})
        self.fields['company'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control' ,'readonly':'readonly'})
        self.fields['address2'].widget.attrs.update({'class': 'form-control' ,'readonly':'readonly'})
        self.fields['address_detail'].widget.attrs.update({'class': 'form-control'})
        self.fields['address_option'].widget.attrs.update({'class': 'form-control'})
        self.fields['business'].widget.attrs.update({'class': 'form-control'})
        self.fields['sectors'].widget.attrs.update({'class': 'form-control'})
        self.fields['tell'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone'].widget.attrs.update({'class': 'form-control'})
        self.fields['tax_bill_mail'].widget.attrs.update({'class': 'form-control'})
        self.fields['ceo'].widget.attrs.update({'class': 'form-control'})
        self.fields['bill_select'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = member_model.CustomerProfile
        fields = ['code','company','address','address2','address_detail','address_option','business','sectors',
                  'tell','tax_bill_mail','phone','ceo','bill_select']

class ProductForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['file'].required = False
        self.fields['text'].required = False

    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'pis','onchange':'readURL(this);','style':'display: none;'}))
    text = forms.CharField(widget=forms.Textarea(attrs={'style':'display: none;'}))

    def clean_file(self):
        content = self.cleaned_data['file']
        if content:
            content_name = content.name.split('.')[-1]
            invalid_list = ['css','js','c','cpp','py','php','exe','bat','reg','vbs','swf','jar','html']
            if content_name in invalid_list:
                raise forms.ValidationError(f'.{content_name} 파일은 업로드 하실 수 없습니다')
        return content

class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]


class SampleSearchForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(SampleSearchForm, self).__init__(*args, **kwargs)
        self.fields['employees'].queryset = User.objects.filter(is_staff=True)
        self.fields['category'].queryset = design_model.Category.objects.filter(level=1)

    class Meta:
        model = managing_model.Sample
        fields = ['category','sectors_category','name','keyword','images']
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control' }),
            'sectors_category': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'keyword': forms.TextInput(attrs={'class': 'form-control'}),
            'images': forms.FileInput(attrs={'class':'form-control'})
        }

design/templates/design/leftsidebar.html
{% extends 'design/base.html'%}
{% load static %}
{% block content%}
<div class="container mb-3 d-block d-lg-none d-xl-none"></div>
<div class="container d-none d-lg-block">
    <div class="hero-content pb-2 pt-3 text-center">
        <h2 class="hero-heading">{% block sidebar_title%}{% endblock %}</h2>
        <p>{% block sidebar_subtitle%}{% endblock %}</p>
    </div>
</div>



<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
            <div style="top: 120px;" class="sticky-top mb-5">
                <div class="sidebar-block">
                    <nav class="nav nav-pills flex-column">
                        <a href="{% url 'design:faq' %}" class="nav-link mb-2" {% block sidebar_active1 %}{%endblock%}>자주 묻는 질문 (F.A.Q)</a>
                        <a href="{% url 'design:order_list' %}" class="nav-link mb-2" {% block sidebar_active2 %}{%endblock%}>
                            {%if user.is_anonymous%}<i class="fas fa-lock text-muted"></i>{% endif %} 주문 리스트
                        </a>
                        <a href="{% url 'design:my_page' %}" class="nav-link mb-2" {% block sidebar_active3 %}{%endblock%}>
                            {%if user.is_anonymous%}<i class="fas fa-lock text-muted"></i>{% endif %} 마이 페이지
                        </a>

                    </nav>
                </div>
            </div>
        </div>
        <div class="col-lg-10 col-xl-8 docs-content text-lg">
            {% block sidebar_content %} {% endblock %}

        </div>
    </div>
</div>

{% endblock %}

design/templates/design/login_form_.html
<form method="post" action="{% url 'design:login'%}" autocomplete="off">
    {% csrf_token %}
    <div class="input-group mb-1">
        <input type="text" name="username" placeholder="Username"
               aria-label="Username"
               aria-describedby="basic-addon1"
               class="form-control" required>
    </div>
    <div class="input-group mb-1">
        <input type="password" name="password" placeholder="password"
               aria-label="password"
               aria-describedby="basic-addon2"
               class="form-control" required>
    </div>
    <button type="submit" class="form-control btn btn-dark">로그인</button>
</form>

design/templates/design/my_page.html
{% extends 'design/leftsidebar.html'%}
{% load static %}
{% block title%}마이페이지{% endblock %}
{% block sidebar_title%}마이페이지{% endblock %}
{% block sidebar_subtitle%}아래 입력하신 사항으로 영수증 처리가 진행됩니다.{% endblock %}
{% block sidebar_active3 %}style="font-weight: bold;"{% endblock %}

{% block sidebar_content%}

 {% if user.is_authenticated %}
<div id="pagesfolder" class="docs-item">
<section>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="block mb-5">
          <div class="block-header"><strong class="text-uppercase">비밀번호 변경</strong></div>
          <div class="block-body">
            <form method="POST" action="{% url 'design:change_password'%}" autocomplete="off">
              {% csrf_token%}
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="id_old_password" class="form-label">기존 비밀번호</label>
                    {{ password_form.old_password }}
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="id_new_password1" class="form-label">새로운 비밀번호</label>
                    {{ password_form.new_password1 }}
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="id_new_password2" class="form-label">새 비밀번호 확인</label>
                    {{ password_form.new_password2 }}
                  </div>
                </div>
              </div>
                     {% if messages %}
                    {% for message in messages %}
            <div role="alert" class="alert alert-danger"> {{message}}</div>
                    {% endfor %}
                    {% endif %}
              <div class="text-center mt-4">
                <button type="submit" class="btn btn-outline-dark"><i class="far fa-save mr-2" id="save_btn"></i>비밀번호 변경</button>
              </div>
            </form>
          </div>
        </div>
        <form method="POST" autocomplete="off">
          {% csrf_token %}
        <div class="block mb-5" >
          <div class="block-header"><strong class="text-uppercase">상세 정보</strong><p class="text-muted">최신 정보에 맞게 적어주세요~</p></div>
          <div class="block-body">
            <form>
              <div class="row">
                <div class="col-sm-3">
                  <div class="form-group">
                    <label for="id_company" class="form-label">상호명</label>
                    {{form.company}}
                  </div>
                </div>
                <div class="col-sm-3">
                  <div class="form-group">
                    <label for="id_tell" class="form-label">전화번호</label>
                    {{form.tell}}
                  </div>
                </div>
                <div class="col-sm-3">
                  <div class="form-group">
                    <label for="id_phone" class="form-label">핸드폰</label>
                     {{form.phone}}
                  </div>
                </div>
                <div class="col-sm-3">
                  <div class="form-group">
                    <label for="id_tax_bill_mail" class="form-label">E-mail</label>
                    {{form.tax_bill_mail}}
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-5">
                   <button class="btn btn-outline-success btn-block" onclick="sample4_execDaumPostcode(); return false; ">
                            <i class="fas fa-map-marker-alt"></i> 주소 검색하기</button>
                </div>
                <div class="col-sm-3">
                  <div class="form-group">

                  </div>
                </div>

                <div class="col-sm-4">

                </div>
              </div>
              <div class="row">

              </div>
              <!-- /.row-->
              <div class="row">
                <div class="col-sm-8">
                  <div class="form-group">
                    <label for="sample4_roadAddress" class="form-label">도로명 주소</label>
                    {{form.address}}
                  </div>
                </div>
                <div class="col-sm-4">
                  <div class="form-group">
                    <label for="sample4_detailAddress" class="form-label">상세 주소</label>
                    {{form.address_detail}}
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-8">
                  <div class="form-group">
                    <label for="sample4_jibunAddress" class="form-label">지번 주소</label>
                    {{form.address2}}
                    <span id="guide" style="color:#999;display:none"></span>
                  </div>
                </div>
                <div class="col-sm-4">
                  <div class="form-group">
                    <label for="sample4_extraAddress" class="form-label">주소 참고항목</label>
                    {{form.address_option}}
                  </div>
                </div>
              </div>
              <!-- /.row-->
              <div class="row">
                <div class="col-sm-6 col-md-3">
                  <div class="form-group">
                    <label for="id_code" class="form-label">사업자 번호</label>
                    {{form.code}}
                  </div>
                </div>
                <div class="col-sm-6 col-md-3">
                  <div class="form-group">
                    <label for="zip" class="form-label">대표자명</label>
                     {{form.ceo}}
                  </div>
                </div>
                <div class="col-sm-6 col-md-3">
                  <div class="form-group">
                    <label for="state" class="form-label">업종</label>
                    {{form.sectors}}
                  </div>
                </div>
                <div class="col-sm-6 col-md-3">
                  <div class="form-group">
                    <label for="country" class="form-label">업태</label>
                    {{form.business}}
                  </div>
                </div>
                <div class="col-sm-12">
                <p class="form-label text-center mt-5 mb-5">* 신용카드 결제가 아닌 경우 받으시려는 영수증의 정보를 정확하게 입력해주시기 바랍니다</p>
                </div>
                <div class="col-sm-12" align="center">
                  <div class="row m-2">
                    <div class="form-group col-md-3 d-flex align-items-center">
                      <input type="radio" name="bill_select" id="option0" value="0"
                      {% if form.bill_select.value == 0 %}checked="checked"{% endif %}>
                      <label for="option0" class="ml-3"><strong class="form-label">세금계산서</strong></label>
                    </div>
                    <div class="form-group col-md-3 d-flex align-items-center">
                      <input type="radio" name="bill_select" id="option1" value="1"
                             {% if form.bill_select.value == 1 %}checked="checked"{% endif %}>
                      <label for="option1" class="ml-3"><strong class="form-label">사업자 지출증빙</strong></label>
                    </div>
                    <div class="form-group col-md-3 d-flex align-items-center">
                      <input type="radio" name="bill_select" id="option2" value="2"
                             {% if form.bill_select.value == 2 %}checked="checked"{% endif %}>
                      <label for="option2" class="ml-3"><strong class="form-label">현금 영수증</strong></label>
                    </div>
                    <div class="form-group col-md-3 d-flex align-items-center">
                      <input type="radio" name="bill_select" id="option3" value="3"
                             {% if form.bill_select.value == 3 %}checked="checked"{% endif %}>
                      <label for="option3" class="ml-3"><strong class="form-label">미발행</strong></label>
                    </div>
                  </div>
                </div>
              </div>
              <div class="text-center mt-4">
                <button type="submit" class="btn btn-outline-dark"><i class="far fa-save mr-2"></i>저장하기</button>
              </div>
            </form>
          </div>
        </div>
        </form>
      </div>
    </div>
  </div>
</section>
</div>

<script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script src="{% static 'design/js/daummap.js'%}"></script>
{%else%}
<div class="row pt-2 mb-7 ">
  <div class="col-lg-3"></div>
  <div class="col-lg-6 ">
    <div class="card mb-3">
      <div class="card-body bg-gray-100">
        <h6 class="text-uppercase mb-4 text-center">로그인 후 이용하실 수 있습니다</h6>
        <form method="post" action="{% url 'design:login'%}?next={{request.get_full_path }}" autocomplete="off">
          {% csrf_token %}
          <div class="input-group">
            <div class="input-group-prepend"><span id="basic-addon1" class="input-group-text"><i
                    class="fas fa-user"></i></span></div>
            <input type="text" name="username" placeholder="Username" aria-label="Username"
                   aria-describedby="basic-addon1"
                   class="form-control" required>
          </div>
          <br>
          <div class="input-group">
            <div class="input-group-prepend"><span id="basic-addon2" class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            <input type="password" name="password" placeholder="password" aria-label="password"
                   aria-describedby="basic-addon2"
                   class="form-control" required>
          </div>
          <br>
          <button type="submit" class="form-control btn btn-dark">로그인</button>
        </form>
      </div>
    </div>


  </div>
  <div class="col-lg-3"></div>

</div>

{% endif %}
<script>
  $('html, body').animate({
        scrollTop: $("#save_btn").offset().top
    }, 1500);
</script>
{% endblock %}