api/urls.py
from django.urls import include, path
from rest_framework import routers
from django.conf import settings

from . import views

app_name = 'rowapi'

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)
# router.register(r'profile', views.ProfileViewSet)
router.register(r'customer_profile', views.CustomerProfileViewSet)
router.register(r'product_view', views.ProductViewSet)
# router.register(r'product', views.ProductTextViewSet)
router.register(r'order_info', views.OrderInfoViewSet, base_name='order_info')
router.register(r'cart_design', views.CartDesignViewSet, base_name='cart_design')
# router.register(r'user_profile', views,ProfileViewSet)

urlpatterns = router.urls
# if settings.DEBUG:
#     urlpatterns += [
#         path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
#     ]

conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path, include
)

urlpatterns = [
    path('minsmine/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('design/', include('design.urls')),
    path('', include('design.urls')),
    path('clovi/', include('managing.urls')),
    path('rowapi/', include('api.urls', namespace='rowapi')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

managing/urls.py
from django.urls import path
from  django.contrib.auth import views as auth_views
from . import views

app_name = 'managing'

urlpatterns = [

    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('password/', views.change_password, name='change_password'),
    path('', views.Main.as_view(), name='main'),

    path('customer_profile/', views.CustomerWriteProfileView.as_view(), name='customer_profile'),
    path('customer_profile/create/', views.CustomerProfileView.as_view(), name='customer_profile_create'),
    path('product_list/', views.ProductListView.as_view(), name='product_list'),

    path('memo/create/<slug:common>/', views.MemoCreateView.as_view(), name='memo_create'),
    path('memo/<int:pk>/update/', views.MemoUpdateView.as_view(), name='memo_update'),
    path('customer_result/', views.CustomerResultView.as_view(), name='customer_result'),

    path('customer/', views.CustomerView.as_view(), name='customer'),
    path('customer/create/', views.CustomerCreateView.as_view(), name='customer_create'),
    path('customer/<int:pk>/update/', views.CustomerUpdateView.as_view(), name='customer_update'),
    path('order_view/<int:state>/', views.OrderView.as_view(), name='order_view'),
    path('order_view/create/', views.OrderCreateAPIView.as_view(), name='order_view_create'),

    path('upload_sample/', views.UploadSampleView.as_view(), name='upload_sample'),


    path('product/', views.ProductView.as_view(), name='product'),
    path('product/create/', views.ProdcutCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('special_price/', views.SpecialPriceView.as_view(), name='special_price'),
    path('special_price/create/', views.SpecialPriceCreateView.as_view(), name='special_price_create'),
    path('special_price/<int:pk>/update/', views.SpecialPriceUpdateView.as_view(), name='special_price_update'),
    path('special_price/<int:pk>/delete/', views.SpecialPriceDeleteView.as_view(), name='special_price_delete'),
    path('sample/', views.SampleView.as_view(), name='sample'),
    path('sample/create/', views.SampleCreateView.as_view(), name='sample_create'),
    path('sample/<int:pk>/update/', views.SampleUpdateView.as_view(), name='sample_update'),
    path('category/', views.CategoryView.as_view(), name='category'),
    path('category/<int:kind>_<int:level>/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:kind>_<int:level>_<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),
    path('discount/', views.DiscountView.as_view(), name='discount'),
    path('img_box/', views.ImageBoxView.as_view(), name='img_box'),
    path('order/<int:common>/', views.OrderListView.as_view(), name='order'),
    path('orders/create/', views.OrdersCreateView.as_view(), name='orders_create'),
    path('orders/<int:pk>/update/', views.OrdersUpdateView.as_view(), name='order_update'),
    path('demand_list/', views.DemandView.as_view(), name='demand_list'),
    path('employees/', views.EmployeesView.as_view(), name='employees'),
    path('employees/create/', views.EmployeesCreateView.as_view(), name='employees_create'),
    path('employees/<int:pk>/update/', views.EmployeesUpdateView.as_view(), name='employees_update'),
    path('deposit/', views.DepositView.as_view(), name='deposit'),
    path('deposit/create/', views.DepositCreateView.as_view(), name='deposit_create'),
    path('deposit/<int:pk>/update/', views.DepositUpdateView.as_view(), name='deposit_update'),
    path('deposit/<int:pk>/delete/', views.DepositDeleteView.as_view(), name='deposit_delete'),
    path('order_deposit/<int:pk>/', views.OrderWithDepositCreateView.as_view(), name='order_deposit'),
    path('order_images/<int:pk>/', views.OrderWithImagesCreateView.as_view(), name='order_images'),
    path('order_images/<int:pk>/delete/', views.OrderWithImagesDeleteView.as_view(), name='order_images_delete'),
    path('payments/', views.PaymentListView.as_view(), name='payment-list'),
    path('bill/<int:pk>/', views.BillView.as_view(), name='bill'),
    path('my_page/', views.MyPageView.as_view(), name='my_page'),
    path('ask/', views.AskView.as_view(), name='ask'),
    path('ask/create/', views.AskCreateView.as_view(), name='ask_create'),
    path('ask/<int:pk>/update/', views.AskUpdateView.as_view(), name='ask_update'),


]

managing/models.py
import re

from django.core.files.uploadedfile import SimpleUploadedFile
from django.utils.safestring import mark_safe
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import Thumbnail, ResizeToFit
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils.models import SoftDeletableModel, TimeStampedModel
from datetime import datetime, timedelta

class Product(TimeStampedModel):
    purchase = models.ForeignKey(
        'member.Profile',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    state = models.IntegerField(
        verbose_name=_('state'),
        blank=True,
        null=True,
    )

    name = models.CharField(
        verbose_name=_('name of product'),
        max_length=255,
        blank=True,
    )

    standard = models.CharField(
        verbose_name=_('standard'),
        max_length=255,
        blank=True,
    )

    purchase_price = models.DecimalField(
        verbose_name=_('purchase_price'),
        blank=True,
        decimal_places=4,
        max_digits=11,
    )

    sale_price = models.DecimalField(
        verbose_name=_('sale_price'),
        blank=True,
        decimal_places=4,
        max_digits=11,
    )

    delivery_charge = models.IntegerField(
        verbose_name=_('delivery charge'),
        blank=True,
    )

    quantity = models.IntegerField(
        verbose_name=_('min quantity'),
        blank=True,
    )

    group = models.CharField(
        verbose_name=_('group of product'),
        max_length=255,
        blank=True,
    )

    manage_code = models.CharField(
        verbose_name=_('manage_code'),
        max_length=255,
        blank=True,
    )

    def upload_to_product(instance, filename):
        return f'product/{instance.purchase}/{filename}'
    product_img = models.ImageField(
        verbose_name=_('product_img'),
        blank= True,
        upload_to= upload_to_product,
    )

    class Meta:
        verbose_name = _('품목')
        verbose_name_plural = _('품목')

    def __str__(self):
        return f'{self.purchase} {self.name} {self.state}'

class Deposit(TimeStampedModel, SoftDeletableModel):
    date = models.DateTimeField(
        verbose_name=_('날짜'),
        blank = True,
        null = True,
    )

    bank = models.CharField(
        verbose_name=_('은행명'),
        max_length=100,
        blank=True,
        null=True,
    )

    part = models.CharField(
        verbose_name=_('입/출금'),
        max_length= 100,
        blank=True,
        null=True,

    )

    name = models.CharField(
        verbose_name=_('입금자명'),
        max_length=255,
        blank=True,
    )

    amount = models.IntegerField(
        verbose_name=_('입금액'),
        blank=True,
    )

    memo = models.CharField(
        verbose_name=_('메모'),
        max_length=255,
        blank=True,
    )

    bill = models.CharField(
        verbose_name=_('영수처리'),
        max_length=255,
        blank=True,
    )
    state = models.BooleanField(
        verbose_name=_('sate of deposit'),
        blank=True,
        default=False,
    )

    class Meta:
        verbose_name = _('입금내역')
        verbose_name_plural = _('입금내역')

    def __str__(self):
        return f'{self.name} {self.amount} {self.memo}'

class OrderWithDeposit(TimeStampedModel):
    order_info_with = models.ForeignKey(
        'design.CustomerOrderInfo',
        on_delete=models.SET_NULL,
        related_name='order_info_with',
        null=True,
        blank=True,
    )
    deposit_with = models.ForeignKey(
        'managing.Deposit',
        on_delete=models.SET_NULL,
        related_name='deposit_with',
        null=True,
        blank=True,
    )
    division =models.IntegerField(
        verbose_name='수동 확인',
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = _('입금 연결')
        verbose_name_plural = _('입금 연결')

    def __str__(self):
        return f'{self.order_info_with} {self.deposit_with}'

class SpecialPrice(TimeStampedModel):
    product = models.ForeignKey(
        'design.ProductText',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    customer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    new_price = models.DecimalField(
        verbose_name=_('new_price'),
        decimal_places=4,
        max_digits=11,
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = _('특별가격')
        verbose_name_plural = _('특별가격')

    def __str__(self):
        return f'{self.product} {self.customer} {self.new_price}'

class Discount(TimeStampedModel):
    product = models.ForeignKey(
        'design.ProductText',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    discount1 = models.IntegerField(
        verbose_name=_('discount1'),
        blank=True,
    )

    discount2 = models.IntegerField(
        verbose_name=_('discount2'),
        blank=True,
    )

    discount3 = models.IntegerField(
        verbose_name=_('discount3'),
        blank=True,
    )

    class Meta:
        verbose_name = _('할인율')
        verbose_name_plural = _('할인율')

    def __str__(self):
        return f'{self.product} {self.discount1} {self.discount2} {self.discount3}'

class Employees(TimeStampedModel, SoftDeletableModel):
    GROUP_EM = Choices(
        (0, '관리자', _('관리자')),
        (1, '팀장', _('팀장')),
        (2, '디자이너', _('디자이너')),
        (3, '알바', _('알바')),
        (4, '기타', _('기타')),
    )

    group = models.IntegerField(
        verbose_name=_('그룹선택'),
        default=2,
        choices=GROUP_EM,
        db_index=True,
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )

    state = models.BooleanField(
        verbose_name=_('state'),
        default=True,
    )

    name = models.CharField(
        verbose_name=_('name of employees'),
        max_length=255,
    )

    join = models.DateField(
        verbose_name=_('Join'),
        blank=True,
        null=True,
    )

    leave = models.DateField(
        verbose_name=_('leave'),
        blank=True,
        null=True,
    )

    cellphone = models.CharField(
        verbose_name=_('cellphone'),
        max_length=255,
        blank=True,
        null=True,
    )

    def upload_to_employees(instance, filename):
        return 'employees/{}/{}'.format(instance.name, filename)
    join_pic = models.ImageField(
        verbose_name=_('join picture'),
        null=True,
        blank= True,
        upload_to= upload_to_employees,
    )
    leave_pic = models.ImageField(
        verbose_name=_('leave picture'),
        null=True,
        blank=True,
        upload_to=upload_to_employees,
    )

    class Meta:
        verbose_name = _('직원')
        verbose_name_plural = _('직원')

    def __str__(self):
        return '{}'.format(self.user)

class Ask(TimeStampedModel, SoftDeletableModel):
    ASK_PART_WHAT_TO_DO = Choices(
        (0, '환불', _('환불')),
        (1, '입금 요청', _('입금 요청')),
        (2, '영수증/계산서', _('영수증/계산서')),
        (3, '기타', _('기타')),
    )

    ask_from = models.CharField(
        verbose_name=_('질문자'),
        max_length=255,
        blank=True,
    )

    ask_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('받는사람'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    ask_part = models.IntegerField(
        verbose_name=_('division of requests'),
        choices=ASK_PART_WHAT_TO_DO,
        db_index=True,
    )

    ask_what = models.CharField(
        verbose_name=_('요청내용'),
        max_length=255,
        blank=True,
    )

    ask_finish = models.BooleanField(
        verbose_name=_('ask_finish'),
        blank=True,
        default=False,
    )

    class Meta:
        verbose_name = _('요청사항')
        verbose_name_plural = _('요청사항')

    def __str__(self):
        return f'{self.ask_from} to {self.ask_to} state:{self.ask_part} {self.ask_what}'

class Sample(TimeStampedModel, SoftDeletableModel):
    category = models.ForeignKey(
        'design.Category',
        blank=True,
        null=True,
        verbose_name=_('카테고리'),
        db_index=True,
        on_delete=models.SET_NULL,
    )
    sectors_category = models.ForeignKey(
        'design.SectorsCategory',
        blank=True,
        null=True,
        verbose_name=_('업종'),
        db_index=True,
        on_delete=models.SET_NULL,
    )

    employees = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        verbose_name=_('직원명'),
        null=True,
        blank=True,
    )

    plush_date = models.DateTimeField(
        verbose_name=_('등록일'),
        auto_now_add=True,
    )

    name = models.CharField(
        verbose_name=_('샘플명'),
        max_length=255,
        blank=True,
    )

    keyword = models.CharField(
        verbose_name=_('키워드'),
        max_length=255,
        blank=True,
    )

    group = models.CharField(
        verbose_name=_('샘플 패키지'),
        max_length=255,
        blank=True,
    )
    state = models.BooleanField(
        verbose_name=_('샘플 상태'),
        default=True,
    )
    link = models.CharField(
        verbose_name=_('링크 url'),
        max_length=255,
        blank=True,
    )

    ASPECT_CHO = Choices(
        (0, '가로', _('가로')),
        (1, '세로', _('세로')),
    )
    aspect = models.IntegerField(
        verbose_name=_('가로 / 세로'),
        default=0,
        choices=ASPECT_CHO,
    )

    def upload_to_sample(instance, filename):
        now = datetime.now()
        nowDate = now.strftime('%Y')
        return f'sample/{instance.category}/{nowDate}/{filename}'

    images = ProcessedImageField(
        verbose_name=_('sample_img'),
        processors=[ResizeToFit(600, 600)],
        blank=True,

managing/templates/managing/ask.html
{% extends 'managing/base.html'%}
{% load static %}
{% load humanize %}
{% block title %}요청 관리{% endblock%}
{% block content%}

<div class="container m-t-50 m-b-30" style="width:800px;">
    <h2 align="center"><b>요청 관리</b>
        <a href="{% url 'managing:ask_create' %}" class="content-modal-btn">
            <i class="ti-plus text-orange"></i>
        </a>
    </h2>
    <br/><br/>
    <div align="center">
        <form role="form" method="GET" autocomplete="off">
            <div class="form-group search-box has-ask">
                {{ data_search_form.q }}
                <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
            </div>
        </form>
    </div>
    <br/>
</div>


{% if messages %}
{% for message in messages %}
<div class="alert alert-icon {% if message.tags == 'success' %}alert-success{%else%}alert-danger{% endif %} alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    <i class="mdi mdi-check-all"></i>
    <strong>{{ message }}</strong>
</div>
{% endfor %}
{% endif %}

<!-- end page title end breadcrumb -->
<div class="card-box">
    <div class="">
        <!-- 판매처  -->
        <div class="tab-pane active" id="home-b1">
            <div class="table-responsive">
                <div class="table-responsive">
                    <table class="table table-hover mails m-0 table table-actions-bar">
                        <thead>
                        <tr>
                            <th width="15%">일자</th>
                            <th width="15%">종류</th>
                            <th>내용</th>
                            <th width="30%">요청/응답</th>
                            <th width="20px;">노출/수정</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for i in ask_list %}
                        <tr
                        {% if i.ask_finish%}
                        style="background-color:#f5ebeb"
                        {% endif %}
                        >
                            <td>
                                {{ i.created|date:"Y. m. d a f" }}
                            </td>
                            <td>
                                {{ i.get_ask_part_display }}
                            </td>
                            <td>
                                {{ i.ask_what|linebreaksbr }}
                            </td>
                            <td>
                                To - <b>{{ i.ask_to.first_name }} </b> <small class=""> _from_ {{ i.ask_from }}님</small>
                            </td>
                            <td>
                                {% if i.ask_finish %}
                                <a href="{% url 'managing:ask_update' i.pk %}" class="content-modal-btn table-action-btn h2">
                                    <i class="mdi mdi-pencil-box-outline text-teal"></i></a>
                                {% else %}
                                <a href="{% url 'managing:ask_update' i.pk %}" class="content-modal-btn table-action-btn h2">
                                    <i class="mdi mdi-pencil-box-outline text-success"></i></a>
                                {% endif %}

                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div> <!-- end table responsive -->
            <div class="row m-t-30">
                <div class="text-center m-t-30">

                    {% if not ask_list %}
                    <h3>검색 된 데이터가 없습니다.</h3>
                    {% endif %}

                    {% if is_paginated %}
                    <nav>
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li>
                                <a href="?page={{ page_obj.previous_page_number }}{% if data_search_form.q.value %}&q={{ data_search_form.q.value }}{% endif %}">
                                    <span>이전</span>
                                </a>
                            </li>
                            {% else %}
                            <li class="disabled">
                                <a href="#">
                                    <span><strike>시작</strike></span>
                                </a>
                            </li>
                            {% endif %}

                            {% for page in page_range %}
                            <li {% if page == page_obj.number %} class="active" {% endif %}>
                                <a href="?page={{ page }}{% if data_search_form.q.value %}&q={{ data_search_form.q.value }}{% endif %}">
                                    {{ page }}</a>
                            </li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                            <li>
                                <a href="?page={{ page_obj.next_page_number }}{% if data_search_form.q.value %}&q={{ data_search_form.q.value }}{% endif %}">
                                    <span>다음</span>
                                </a>
                            </li>
                            {% else %}
                            <li {% if not page_obj.has_next %}class="disabled" {% endif %}>
                                <a href="#">
                                    <strike>끝</strike>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

managing/templates/managing/ask_create.html
{% extends 'managing/base.html'%}
{% load static %}
{% block title %}요청 등록{% endblock%}

{% block content%}
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h4 class="page-title"><a href="{% url 'managing:ask' %}">요청 관리</a> / 요청 등록</h4>
        </div>
    </div>
</div>
<!-- end page title end breadcrumb -->
<div class="card-box">

    <div class="row">
        <div class="col-sm-12">
            <a href="{% url 'managing:ask' %}">
                <button class="btn btn-teal btn-rounded btn-md waves-effect waves-light m-b-30">요청 목록
                </button>
            </a>
        </div>
    </div>
 {% include 'managing/ask_create_form_.html'%}

</div>


{% endblock %}

managing/templates/managing/deposit_create.html
{% extends 'managing/base.html'%}
{% load static %}
{% block title %}입금 등록{% endblock%}

{% block content%}
<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h4 class="page-title"><a href="{% url 'managing:deposit' %}">입금 관리</a> / 입금 등록</h4>
        </div>
    </div>
</div>
<!-- end page title end breadcrumb -->
<div class="card-box">

    <div class="row">
        <div class="col-sm-12">
            <a href="{% url 'managing:deposit' %}">
                <button class="btn btn-teal btn-rounded btn-md waves-effect waves-light m-b-30">입금 목록
                </button>
            </a>
        </div>
    </div>

    {% include 'managing/deposit_create_form_.html' %}

</div>

{% endblock %}

managing/templates/managing/special_price.html
{% extends 'managing/base.html'%}
{% load static %}
{% load humanize %}
{% block title %}특별단가 관리{% endblock%}
{% block content%}

<div class="container m-t-50 m-b-30" style="width:800px;">
    <h2 align="center">
        <a href="{% url 'managing:product' %}">
            <small>품목 리스트</small>
        </a>
        <b>/ 특별단가 관리</b>
        {% if group_name != '디자이너'%}
        <a href="{% url 'managing:special_price_create' %}" class="content-modal-btn">
            <i class="ti-plus text-success"></i>
        </a>
        {% endif %}
    </h2>
    <br/><br/>
    <div align="center">
        <form role="form" method="GET" autocomplete="off">
            <div class="form-group search-box has-special">
                {{ data_search_form.q }}
                <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
            </div>
        </form>
    </div>
    <br/>
</div>


{% if messages %}
{% for message in messages %}
<div class="alert alert-icon {% if message.tags == 'success' %}alert-success{%else%}alert-danger{% endif %} alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    <i class="mdi mdi-check-all"></i>
    <strong>{{ message }}</strong>
</div>
{% endfor %}
{% endif %}
<!-- end page title end breadcrumb -->
<div class="card-box">
    <div class="">
        <!-- 판매처  -->
        <div class="tab-pane active" id="home-b1">
            <div class="table-responsive">
                <div class="table-responsive">
                    <table class="table table-hover mails m-0 table table-actions-bar">
                        <thead>
                        <tr>
                            <th>업체 정보</th>
                            <th>품목 정보</th>
                            <th>특별 가격</th>
                            {% if group_name != '디자이너'%}
                            <th>수정</th>
                            <th>삭제</th>
                            {% endif %}
                        </tr>
                        </thead>

                        <tbody>
                        {% for i in object_list %}
                        <tr>
                            <td>
                                {% if i.customer.profile.company %}
                                <b class="text-custom">{{ i.customer.profile.company }}</b><br>
                                {% endif %}
                                {% if i.customer.profile.company_keyword %}
                                {{ i.customer.profile.company_keyword }}<br>
                                {% endif %}
                                {% if i.customer.profile.tell %}
                                {{ i.customer.profile.tell }}<br>
                                {% endif %}
                                {% if i.customer.profile.address %}
                                {{ i.customer.profile.address }}<br>
                                {% endif %}

                            </td>
                            <td>
                                {% if i.product.standard %}
                                <b class="text-purple">{{ i.product.standard }}</b>
                                <span class="text-muted"> {{ i.product.supplier.profile.company }}</span><br>

                                {% endif %}
                                 {% if i.product.gram %}
                                {{ i.product.gram }}<br>
                                {% endif %}
                                {% if i.product.horizontal and i.product.vertical%}
                                {{ i.product.horizontal|floatformat:'0'|intcomma }} x
                                {{ i.product.vertical|floatformat:'0'|intcomma }}<br>
                                {% endif %}
                                {% if i.product.etc %}
                                {{ i.product.etc }}<br>
                                {% endif %}
                                {% if i.product.memo %}
                                {{ i.product.memo }}<br>
                                {% endif %}

                            </td>
                             <td>
                                 {% if i.product.buy_price %}
                                 <strike class="text-danger">{{ i.product.sell_price|floatformat:'0'|intcomma }}</strike><br>
                                {% endif %}

                                 <span class="text-teal">{{ i.new_price|floatformat:'0'|intcomma  }}</span>
                            </td>


                             {% if group_name != '디자이너'%}
                            <td>
                                <a href="{% url 'managing:special_price_update' i.pk %}" class="table-action-btn h2 content-modal-btn"><i
                                        class="mdi mdi-pencil-box-outline text-success"></i></a>
                            </td>
                             <form method="post" action="{%url 'managing:special_price_delete' i.pk %}">{% csrf_token %}
                                <td>
                                    <button class="btn btn-danger btn-xs" onclick="return confirm('삭제하시겠습니까?');">
                                       <b>X</b>
                                    </button>
                                </td>
                            </form>
                            {% endif %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div> <!-- end table responsive -->
            <div class="row m-t-30">
                <div class="text-center m-t-30">

                    {% if not object_list %}
                    <h3>검색 된 데이터가 없습니다.</h3>
                    {% endif %}

                    {% if is_paginated %}
                    <nav>
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li>
                                <a href="?page={{ page_obj.previous_page_number }}{% if data_search_form.q.value %}&q={{ data_search_form.q.value }}{% endif %}">
                                    <span>이전</span>
                                </a>
                            </li>
                            {% else %}
                            <li class="disabled">
                                <a href="#">
                                    <span><strike>시작</strike></span>
                                </a>
                            </li>
                            {% endif %}

                            {% for page in page_range %}
                            <li {% if page == page_obj.number %}class="active" {% endif %}>
                                <a href="?page={{ page }}{% if data_search_form.q.value %}&q={{ data_search_form.q.value }}{% endif %}">
                                    {{ page }}</a>
                            </li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                            <li>
                                <a href="?page={{ page_obj.next_page_number }}{% if data_search_form.q.value %}&q={{ data_search_form.q.value }}{% endif %}">
                                    <span>다음</span>
                                </a>
                            </li>
                            {% else %}
                            <li {% if not page_obj.has_next %}class="disabled" {% endif %}>
                                <a href="#">
                                    <strike>끝</strike>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                    {{page_obj}}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}